#ifndef __TLFLOATVERSION_HPP_INCLUDED__
#define __TLFLOATVERSION_HPP_INCLUDED__

#define TLFLOAT_VERSION_MAJOR 1
#define TLFLOAT_VERSION_MINOR 16
#define TLFLOAT_VERSION_PATCH 0

#define TLFLOAT_COMPILER_SUPPORTS_INT128
#define TLFLOAT_COMPILER_SUPPORTS_ISOFLOAT128
/* #undef TLFLOAT_COMPILER_SUPPORTS_FLOAT128 */
#define TLFLOAT_LONGDOUBLE_IS_FLOAT128
#define TLFLOAT_COMPILER_SUPPORTS_FP16

/* #undef TLFLOAT_ENABLE_INTSQRT */

#endif
