#include <stdlib.h>
#include <stdio.h>

#include <zerodj/controls/zdj_controls.h>
#include <zerodj/signal/deck/zdj_deck_manager.h>

zdj_control_map_id_t zdj_control_active_map;

void zdj_activate_control_map( zdj_control_map_id_t map_id ) {
    printf( "zdj_activate_control_map: %s\n", zdj_control_map_name[ map_id ] );
    zdj_deactivate_all_controls( );
    switch ( map_id ) {
        case ZDJ_CONTROL_MAP_MENU_BASE:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_PRESS_2 ); // long press for edit mode
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_MENU_DJ_ROOT:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_LOG:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_PRESS_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_TEXT_INPUT:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_SDK_TEST:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_SOUNDCARD_PANEL:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            // zdj_activate_control( ZDJ_UI_CONTROL_SCROLL_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_NEXT_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_PREV_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
    case ZDJ_CONTROL_MAP_SOUNDCARD_OPTIONS_PANEL:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_ASSIST_PANEL:
        case ZDJ_CONTROL_MAP_DEBUG_PANEL:
        case ZDJ_CONTROL_MAP_RECORDING_PANEL:
        case ZDJ_CONTROL_MAP_SETTINGS_PANEL:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            // zdj_activate_control( ZDJ_UI_CONTROL_SCROLL_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_NEXT_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_PREV_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_IMAGE_VIEWER:
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_STATION_1_EDIT_SONG:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_EDIT_CUEPOINT:
        case ZDJ_CONTROL_MAP_STATION_1_EDIT_BEATGRID:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            // zdj_activate_control( ZDJ_UI_CONTROL_SCROLL_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_STATION_2_EDIT_SONG:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            // zdj_activate_control( ZDJ_UI_CONTROL_SCROLL_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_EDIT_CUEPOINT:
        case ZDJ_CONTROL_MAP_STATION_2_EDIT_BEATGRID:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            // zdj_activate_control( ZDJ_UI_CONTROL_SCROLL_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_LIB_SONG_DEBUG:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            // zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_0 );
            // zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_0 );
            // zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_ADJUST_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_1_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_STATION_1_EMPTY:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_MOM_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_2_BASS_SWAP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_2_BASS_SWAP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_TRIM:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TRIM );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PFL_TRIM );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PFL_TOGGLE_MUTE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_LOOP:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_RESET_TO_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_SET_ORIGIN );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_RESET_TO_ORIGIN );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 ); // Toggle quant
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_LOOP_OFF:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_SET );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH_ALT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_ALT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_SET_ORIGIN );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_RESET_TO_ORIGIN );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_QUANT_TOGGLE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 ); // Toggle quant
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_LOOP_ON:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_SET );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_START_ALT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_LENGTH_ALT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_LOOP_RESET_TO_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TONE_2_RELEASE_0 ); // Toggle quant
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_SYNC:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_CONTROL_SYNC_TOGGLE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SYNC_MULT );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_1_FILT:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_1_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FILTER_1 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FILTER_2 );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FILTER_RESET );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_PRESS_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;

        case ZDJ_CONTROL_MAP_STATION_2_EMPTY:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_ADJUST_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_MOM_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_2_BASS_SWAP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_1 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_2_BASS_SWAP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_TRIM:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TRIM );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PFL_TRIM );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PFL_TOGGLE_MUTE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_LOOP:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_START_ALT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_RESET_TO_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_SET_ORIGIN );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_RESET_TO_ORIGIN );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_LOOP_ON:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_START_ALT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_LENGTH_ALT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_RESET_TO_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_LOOP_OFF:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_TOGGLE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_LENGTH_ALT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_LOOP_RESET_TO_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_ALT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_LENGTH );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_SET_ORIGIN );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SKIP_RESET_TO_ORIGIN );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_QUANT_TOGGLE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_SYNC:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_CONTROL_SYNC_TOGGLE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SYNC_MULT );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_2_FILT:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_START );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_END );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_CUE_NEXT );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_3 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_4 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_5 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_6 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_HOTCUE_7 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_SCRUB_ALT_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_2_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_1 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_2 );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FILTER_RESET );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_PRESS_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_EXT_MOM_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_EXT_EQ:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_2_BASS_SWAP );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_LO );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_MID );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_EQ_HI );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_EXT_TRIM:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_TRIM );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_PFL_TRIM );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_PFL_TOGGLE_MUTE );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_EXT_SYNC:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_CONTROL_SYNC_TOGGLE );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_SYNC_MULT );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
        case ZDJ_CONTROL_MAP_STATION_EXT_FILT:
            zdj_activate_control( ZDJ_DECK_CONTROL_LR_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_CUE_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_RECORD_VOL );
            zdj_activate_control( ZDJ_DECK_CONTROL_XFADE );
            zdj_activate_control( ZDJ_DECK_1_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_2_CONTROL_FADE );
            zdj_activate_control( ZDJ_DECK_CONTROL_TOGGLE_RECORD );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_PLAY_PAUSE );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_SCRUB );
            zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO );
            // zdj_activate_control( ZDJ_DECK_XPORT_CONTROL_TEMPO_FINE );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_FILTER_0 );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_FILTER_1 );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_FILTER_2 );
            zdj_activate_control( ZDJ_DECK_EXT_CONTROL_FILTER_RESET );
            zdj_activate_control( ZDJ_UI_CONTROL_JOG_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_NAV_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_0 ); 
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_2_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_3_RELEASE_0 );
            zdj_activate_control( ZDJ_UI_CONTROL_FN_1_RELEASE_2 );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PANEL );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_DEBUG_WIDGET );
            zdj_activate_control( ZDJ_UI_CONTROL_TOGGLE_PERF_WIDGET );
            break;
    }

    zdj_control_active_map = map_id;

    // Let the Deck Manager know we changed maps so it can track the most recent station
    zdj_deck_manager_set_recent_playback_station_for_map( map_id );
    
    // Re-activate special control handler
    for( int i=0; i<5; i++ ) {
        if( zdj_special_control_handlers[ i ].active ) {
            zdj_activate_control( zdj_special_control_handlers[ i ].id );
        }
    }
}