#ifndef ZDJ_HEALTH_TYPE_H
#define ZDJ_HEALTH_TYPE_H

typedef enum {
    ZDJ_HEALTH_STATUS_UNKNOWN,
    ZDJ_HEALTH_STATUS_OKAY,
    ZDJ_HEALTH_STATUS_FIRST_CRASH,
    ZDJ_HEALTH_STATUS_MISSING_DEPENDENCY,
    ZDJ_HEALTH_STATUS_MISSING,
    ZDJ_HEALTH_STATUS_SDL_FAILED
} zdj_health_status_t;

#endif